package controllers

import (
	"fmt"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/golang-jwt/jwt/v5"
	"github.com/spf13/viper"
	"golang.org/x/crypto/bcrypt"
	"gopkg.in/gomail.v2"

	"www.github.com/ic-ETITE-24/icetite-24-backend/internal/database"
	"www.github.com/ic-ETITE-24/icetite-24-backend/internal/models"
)

func CreateUser(c *fiber.Ctx) error {
	var createUser models.CreateUser

	if err := c.BodyParser(&createUser); err != nil {
		return c.Status(fiber.StatusBadRequest).
			JSON(fiber.Map{"message": "Please send complete data"})
	}

	dob, _ := time.Parse("2006-01-02", createUser.DateOfBirth)

	hashedPassword, _ := bcrypt.GenerateFromPassword([]byte(createUser.Password), 10)

	user := models.User{
		FirstName:   createUser.FirstName,
		LastName:    createUser.LastName,
		Email:       createUser.Email,
		Password:    string(hashedPassword),
		Gender:      createUser.Gender,
		DateOfBirth: dob,
		Bio:         createUser.Bio,
		TeamId:      0,
		IsLeader:    false,
		IsApproved:  false,
		PhoneNumber: createUser.PhoneNumber,
		College:     createUser.College,
		Github:      createUser.Github,
	}

	if result := database.DB.Create(&user); result.Error != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"message": result.Error.Error()})
	}

	return c.Status(fiber.StatusOK).
		JSON(fiber.Map{"message": "Successfully created user", "user": user})
}

func ForgotEmail(c *fiber.Ctx) error {

	email := c.Params("email")

	var check models.User
	database.DB.Find(&check, "email = ?", email)
	if (check == models.User{}) {
		return c.Status(fiber.StatusBadRequest).JSON(&fiber.Map{
			"Status": false,
			"Error":  "The email address given doesn't exist",
		})
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"exp":   time.Now().Add(time.Minute * 2).Unix(),
		"email": email,
	})
	Token, err := token.SignedString([]byte(viper.GetString("ACCESS_SECRET_KEY")))

	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(&fiber.Map{
			"Status": false,
			"Error":  "Failed to create an JWT token",
		})
	}

	msg := gomail.NewMessage()
	msg.SetHeader("From", viper.GetString("SENDER_MAIL"))
	msg.SetHeader("To", email)
	msg.SetHeader("Subject", "Email to reset the password for the hack")
	url := fmt.Sprintf("%s%s", viper.GetString("URL"), Token)
	body := fmt.Sprintf(
		"%s\n%s %s\n%s",
		"This email was auto generated by /some name/ to reset password.",
		"You can click the link below for resetting the password",
		url, "If this wasn't requested by you then ignore it")
	msg.SetBody("text/plain", body)

	d := gomail.NewDialer("smtp.gmail.com", 587, viper.GetString("SENDER_MAIL"), viper.GetString("SENDER_PASS"))
	if err := d.DialAndSend(msg); err != nil {
		fmt.Println(err)
		return c.Status(fiber.StatusInternalServerError).JSON(&fiber.Map{
			"Status": false,
			"Error":  "Something went wrong while sending the email",
		})
	}

	return c.Status(fiber.StatusAccepted).JSON(&fiber.Map{
		"Status": true,
		"data":   Token,
	})
}

func ResetPassword(c *fiber.Ctx) error {
	token := c.Params("Token")

	type Password struct {
		Password     string `json:"password"`
		Confirm_pass string `json:"confirm_pass"`
	}

	Token, _ := jwt.Parse(token, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("Invalid signing method")
		}

		return []byte(viper.GetString("ACCESS_SECRET_KEY")), nil
	})

	if decoded, ok := Token.Claims.(jwt.MapClaims); ok {
		if float64(time.Now().Unix()) > decoded["exp"].(float64) {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
				"Error": "Token Expired",
			})
		}
		email := decoded["email"]
		var user models.User
		database.DB.Find(&user, "email = ?", email)
		if (user == models.User{}) {
			return c.Status(fiber.StatusBadRequest).JSON(&fiber.Map{
				"Error": "The email doesn't exists",
			})
		}
		var req = new(Password)
		if err := c.BodyParser(&req); err != nil {
			return c.Status(fiber.StatusBadRequest).JSON(&fiber.Map{
				"Error": "Error rose while parsing through the body",
			})
		}
		if req.Password != req.Confirm_pass {
			return c.Status(fiber.StatusBadRequest).JSON(&fiber.Map{
				"Error": "Password and confirm password are not the same",
			})
		}
		hashed_password, _ := bcrypt.GenerateFromPassword([]byte(req.Password), 10)
		user.Password = string(hashed_password)
		database.DB.Save(user)
		return c.Status(fiber.StatusAccepted).JSON(&fiber.Map{
			"Message": "The password has been updated",
		})
	}
	return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{"message": "Invalid Token"})
}
