name: Deploy and Health Check

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  deploy_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Server and Pull Repository
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p 22 "cd icetite-24-backend && git pull origin main" << EOF 
        env:
          SSH_AUTH_SOCK: /dev/null  # Disable SSH agent for password-based authentication

      - name: Run Makefile Command
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -p 22 "cd icetite-24-backend && make build" << EOF
        env:
          SSH_AUTH_SOCK: /dev/null

      - name: Health Check
        run: |
          health_check_result=$(curl -sS http://localhost:8080/ping)
          if [[ "$health_check_result" == "pong" ]]; then
            echo "Health check successful: pong received."
          else
            echo "Health check failed: Expected 'pong', but received '$health_check_result'."
            exit 1
          fi

# Don't forget to set your secrets in the GitHub repository settings for SSH_PASSWORD, SERVER_HOST, SERVER_USERNAME, and SERVER_PORT.
